@startuml
abstract class Shape {
- String color
- boolean filled
~ <<Create>> Shape()
~ <<Create>> Shape(String,boolean)
+ String getColor()
+ void setColor(String)
+ boolean isFilled()
+ void setFilled(boolean)
+ {abstract}void getArea(double)
+ {abstract}void getPerimeter(double)
+ String toString()
}
class Main {
+ {static} void main(String[])
}
@enduml